apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: otel-collector-conf
    component: otel-collector-conf
data:
  otel-collector-conf: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      jaeger:
        protocols:
          thrift_http:
            endpoint: "0.0.0.0:14268"
    
    processors:
    
    exporters:
      logging:
        verbosity: detailed
      otlp/jaeger:
        endpoint: "localhost:7878"
        tls:
          insecure: true
    
    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: []
          exporters: [logging, otlp/jaeger]
