apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: clara
spec:
  selector:
    app: otel-collector
  ports:
    - name: http-otlp
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: grpc-otlp
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: http-jaeger
      protocol: TCP
      port: 14268
      targetPort: 14268

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-deployment
  namespace: clara
  labels:
    app: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - command:
            - "/otelcol"
            - "--config=/conf/otel-collector-config.yaml"
          image: otel/opentelemetry-collector:0.92.0
          name: otel-collector
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 4318
            - containerPort: 4317
            - containerPort: 14268
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-conf
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
