receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14268"

processors:

exporters:
  logging:
    verbosity: detailed
  otlp/jaeger:
    endpoint: http://host.docker.internal:7878 # Has to be changed for deployment to CLARA's FQDN; this config is for running this container on local machines.
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: []
      exporters: [logging, otlp/jaeger]
