app:
  block-after-finish: false
  log-config: true

aggregation:
  platforms:
    kubernetes:
      namespaces:
        - TBD
      aggregators:
        kube-api:
        dns:
          logs-since-time: 2024-04-27T00:00:00Z
        open-telemetry:
          listen-port: 7878
          listen-duration: 60 seconds
        syft-sbom:
          sbom-file-path: sbom/
          use-stored-sbom-files: false

merge:
  comparison-strategy: Equals
  show-messaging-communications-directly: false

filter:
  remove-component-versions: false
  remove-component-endpoints: false
  remove-components-by-names:
    - otel-collector-service

export:
  exporters:
    graphviz:
      output-type: SVG
      output-file: generated/architecture.svg
    gropius:
      enabled: false
      project-id: tbd
      graphql-backend-url: http://devonport.informatik.uni-stuttgart.de:8082/graphql
      graphql-backend-authentication:
        authentication-url: http://devonport.informatik.uni-stuttgart.de:3000/authenticate/oauth/5590d02a-99b5-4864-be49-e45f426332ab/token
        username: ${CLARA_GROPIUS_GRAPHQL_USERNAME}
        password: ${CLARA_GROPIUS_GRAPHQL_PASSWORD}
        client-id: ${CLARA_GROPIUS_GRAPHQL_CLIENT_ID}
      component-handling: Delete
      export-libraries: false
