app:
  block-after-finish: true
  log-config: true

aggregation:
  platforms:
    kubernetes:
      namespaces:
        - default
      aggregators:
        kube-api:
        dns:
          logs-since-time: ${CLARA_PLATFORMS_KUBERNETES_AGGREGATORS_DNS_LOGS_SINCE_TIME:-2024-05-07T06:00:00Z}
        open-telemetry:
          listen-port: 7878
          listen-duration: 90 seconds
        syft-sbom:
          sbom-file-path: sbom/
          use-stored-sbom-files: true

merge:
  comparison-strategy: Equals
  show-messaging-communications-directly: false

filter:
  remove-component-versions: false
  remove-component-endpoints: false
  remove-components-by-names:
    - otel-collector-service

export:
  exporters:
    graphviz:
      output-type: SVG
      output-file: generated/architecture.svg
    gropius:
      project-id: ${CLARA_GROPIUS_GRAPHQL_PROJECT_ID}
      graphql-backend-url: ${CLARA_GROPIUS_GRAPHQL_BACKEND_URL}
      graphql-backend-authentication:
        authentication-url: ${CLARA_GROPIUS_GRAPHQL_AUTHENTICATION_URL}
        username: ${CLARA_GROPIUS_GRAPHQL_USERNAME}
        password: ${CLARA_GROPIUS_GRAPHQL_PASSWORD}
        client-id: ${CLARA_GROPIUS_GRAPHQL_CLIENT_ID}
      component-handling: Delete
      export-libraries: false
