app:
  block-after-finish: false
  log-config: true

aggregation:
  platforms:
    kubernetes:
      namespaces:
        - clara
      aggregators:
        kube-api:
        dns:
          logs-since-time: 2024-03-01T00:00:00Z
        open-telemetry:
          listen-port: 7878
          listen-duration: 60 seconds

merge:
  comparison-strategy: Equals
  show-messaging-communications-directly: False

filter:
  remove-component-endpoints: false
  remove-components-by-names:
    - my-otel-demo-otelcol
    - my-otel-demo-jaeger-.*

export:
  exporters:
    graphviz:
      output-type: SVG
      output-file: generated/architecture.svg
    gropius:
      project-id: 30a47418-2089-4283-8a06-1103aa71f017
      graphql-backend-url: http://devonport.informatik.uni-stuttgart.de:8082/graphql
      graphql-backend-authentication:
        authentication-url: http://devonport.informatik.uni-stuttgart.de:3000/authenticate/oauth/da7ea55f-da6a-49f4-8bba-cd8dd29f2ff5/token
        username: ${CLARA_GROPIUS_GRAPHQL_USERNAME}
        password: ${CLARA_GROPIUS_GRAPHQL_PASSWORD}
        client-id: ${CLARA_GROPIUS_GRAPHQL_CLIENT_ID}
      component-handling: Delete
