app:
  block-after-finish: false
  log-config: true

aggregation:
  platforms:
    kubernetes:
      namespaces:
        - "*"
      aggregators:
        pod:
        service:
        dns:
          logs-since-time: 2024-02-01T00:00:00Z
        open-telemetry:
          enable: false
          listen-port: 7878
          listen-duration: 10 seconds

export:
  exporters:
    graphviz:
      output-type: svg
      output-file: generated/architecture.svg
    gropius:
      graphql-backend-url: ${CLARA_GROPIUS_URL}
      graphql-backend-token: ${CLARA_GROPIUS_TOKEN}
