app:
  block-after-finish: false

aggregation:
  platforms:
    kubernetes:
      namespaces:
        - "*"
      aggregators:
        pod:
        service:
        dns:
          logs-since-time: 2024-01-01T00:00:00Z
        open-telemetry:
          listen-port: 7878
          listen-duration: 10 seconds

export:
  exporters:
    graphviz:
      output-type: svg
      output-file: generated/architecture.svg
    gropius:
