aggregation:
  platforms:
    kubernetes:
      namespaces:
        - "default"
        - "test"
      aggregators:
        pod:
        service:
        dns:

export:
  exporters:
    graphViz:
      outputType: svg
      outputFile: generated/architecture.svg
    gropius:
