aggregation:
  platforms:
    kubernetes:
      includeKubeNamespaces: true
      namespaces:
        - "*"
      aggregators:
        pod:
        service:
        dns:

export:
  exporters:
    graphViz:
      outputType: svg
      outputFile: generated/architecture.svg
    gropius:
