name: Documentation

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  publish-documentation:

    runs-on: [ ubuntu-latest ]

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install MkDocs and dependencies
        run: pip install -r docs/requirements.txt

      - name: Set Git user info
        run: >
          git config user.name "Documentation Bot" &&
          git config user.email "clara-documentation-bot@noreply.github.com"

      - name: Checkout the current gh-pages branch
        run: git fetch origin gh-pages --depth=1

      - name: Build and deploy documentation on GitHub pages
        run: cd docs && mkdocs gh-deploy --force --clean --verbose
